const CONFIG_CODES = {
    CONFIG_INVALID: 'ERR_DS_EXPRESS_ERRORS_CONFIG_INVALID',
    CONFIG_ALREADY_SET: 'ERR_DS_EXPRESS_ERRORS_CONFIG_ALREADY_SET',
    CONFIG_SETTING_MISSING: 'ERR_DS_EXPRESS_ERRORS_CONFIG_SETTING_MISSING'
}

const GLOBAL_HANDLER_CODES = {
    GLOBAL_HANDLER_ALREADY_SET: 'ERR_DS_EXPRESS_ERRORS_GLOBAL_HANDLER_ALREADY_SET',
    GLOBAL_HANDLER_INVALID: 'ERR_DS_EXPRESS_ERRORS_GLOBAL_HANDLER_INVALID',
    GLOBAL_HANDLER_SETTING_MISSING: 'ERR_DS_EXPRESS_ERRORS_GLOBAL_HANDLER_SETTING_MISSING'
}

module.exports = { CONFIG_CODES, GLOBAL_HANDLER_CODES}